// AUTO-GENERATED by `npm run generate-tools`. Do not edit by hand.
// Source: <flutter-app>/lib/features/shared/models/tool.dart
//
// Re-run `npm run generate-tools` (or `npm run dev` / `npm run build`) after
// adding/removing tools in the Flutter app to refresh this file.

import { Icon } from "@raycast/api";

export interface ToolEntry {
  name: string;
  category: string;
  route: string;
  deepLink: string;
  description: string;
  supportsInput: boolean;
  /** Name of a Raycast `Icon.*` enum member (e.g. "Braces", "Code"). */
  iconName: string;
  keywords: string[];
}

import data from "./tools.json";

export const tools: ToolEntry[] = data as ToolEntry[];

/**
 * Resolve a tool's `iconName` (a string emitted by `generate-tools.mjs`)
 * to the actual Raycast `Icon` value. Falls back to `Icon.Circle` if the
 * name is unknown (e.g. an icon was removed in a future Raycast release).
 *
 * The lookup is intentionally string-based so that the JSON stays portable
 * and TypeScript only depends on the Raycast API for the final lookup.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const ICON_REGISTRY: Record<string, any> = Icon as unknown as Record<string, any>;

export function iconFor(tool: ToolEntry): keyof typeof Icon {
  const v = ICON_REGISTRY[tool.iconName];
  return (v ?? Icon.Circle) as keyof typeof Icon;
}

/**
 * Category display order. Mirrors the order in
 * `lib/features/shared/models/category_config.dart` so the Raycast list
 * matches the in-app grid. Categories not listed here sort alphabetically
 * after the known ones.
 */
export const CATEGORY_ORDER: ReadonlyArray<string> = [
  "Formatters",
  "Utilities",
  "Encoders/Decoders",
  "Converters",
  "Code Converters",
  "Validators",
  "Minifiers",
  "Viewers",
  "Previewers",
  "Cryptography",
  "DateTime Utilities",
  "QR Code",
  "Settings",
];

export function categorySortIndex(category: string): number {
  const idx = CATEGORY_ORDER.indexOf(category);
  return idx === -1 ? Number.MAX_SAFE_INTEGER : idx;
}
